add_subdirectory(SEGGER_RTT)
add_subdirectory(Front)
add_subdirectory(Button)
add_subdirectory(ChipDrivers)
add_subdirectory(EasyLog)
add_subdirectory(Kfifo)
add_subdirectory(LetterShell)
add_subdirectory(Minimp3)
add_subdirectory(Modbus)
add_subdirectory(Protocol)
add_subdirectory(Soc)
# add_subdirectory(SeggerHardFault)
